site:
  base-url: "/YRBS_Machine_Learning_Notebook/"

project:
  type: website
  output-dir: docs
  resources:
    - R/
    - data/

website:
  title: "Machine Learning Notes"
  navbar:
    left:
      - href: index.html
        text: Home
      - href: about.html
        text: About
      - text: Models
        menu:
          - href: models/datasets.html
            text: Data and Research Question
          - href: models/logistic.html
            text: Logistic Regression
          - href: models/lasso.html
            text: Lasso Regression
          - href: models/trees.html
            text: Decision Trees
          - href: models/random-forest.html
            text: Random Forest

format:
  html:
    theme: sketchy
    css: styles.css
    toc: true


